/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * SQL expression to be used when selecting the column (name will be the alias
 */
export type SchemaColumnExpr = string;
/**
 * Validate column name
 */
export type SchemaColumnName = string;
/**
 * Validate column data_tests
 */
export type SchemaColumnDataTests = (
  | ("not_null" | "unique")
  | {
      unique: {
        config: {
          where: SchemaColumnExpr;
        };
      };
    }
  | {
      accepted_values: {
        quote?: boolean;
        values: string[];
      };
    }
  | {
      relationships: {
        field: SchemaColumnName;
        to: string;
      };
    }
)[];
