/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for lightdash AI hints
 */
export type SchemaLightdashAIHint = string | string[];
/**
 * Schema for lightdash required filters
 */
export type SchemaLightdashRequiredFilters = {
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: string;
}[];

export interface SchemaLightdashTable {
  ai_hint?: SchemaLightdashAIHint;
  group_details?: SchemaLightdashGroupDetails;
  group_label?: string;
  label?: string;
  required_attributes?: SchemaLightdashRequiredAttributes;
  required_filters?: SchemaLightdashRequiredFilters;
  sql_filter?: string;
  sql_where?: string;
}
/**
 * Schema for lightdash group details
 */
export interface SchemaLightdashGroupDetails {
  /**
   * This interface was referenced by `SchemaLightdashGroupDetails`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: {
    /**
     * The label of the group
     */
    label?: string;
    /**
     * The description of the group
     */
    description?: string;
  };
}
/**
 * Schema for lightdash required attributes
 */
export interface SchemaLightdashRequiredAttributes {
  /**
   * This interface was referenced by `SchemaLightdashRequiredAttributes`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: string | string[];
}
