/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validates schema for models
 */
export type SchemaModel =
  | SchemaModelTypeStgSelectSource
  | SchemaModelTypeStgSelectModel
  | SchemaModelTypeStgUnionSources
  | SchemaModelTypeIntSelectModel
  | SchemaModelTypeIntJoinColumn
  | SchemaModelTypeIntJoinModels
  | SchemaModelTypeIntLookbackModel
  | SchemaModelTypeIntRollupModel
  | SchemaModelTypeIntUnionModels
  | SchemaModelTypeMartSelectModel
  | SchemaModelTypeMartJoinModels;
/**
 * Validate group reference
 */
export type SchemaModelGroup = string;
/**
 * Validate model topic
 */
export type SchemaModelTopic = string;
/**
 * Validate model name
 */
export type SchemaModelName = string;
/**
 * Description for the model that will appear as a hover tooltip in Lightdash
 */
export type SchemaModelDescription = string;
/**
 * Validate model tags
 */
export type SchemaModelTags = (
  | string
  | {
      tag: string;
      type?: "exclude" | "inherit" | "local";
    }
)[];
/**
 * Materialization Configuration
 */
export type SchemaModelMaterialization =
  | {
      type: "ephemeral";
    }
  | {
      type: "incremental";
      database?: SchemaModelDatabase;
      format?: SchemaModelFormat;
      partitions?: SchemaModelPartitions;
      strategy?: ModelIncrementalStrategySchemaJson;
    };
/**
 * Database override for where the model will be materialized
 */
export type SchemaModelDatabase = string;
/**
 * Open table format for the model
 */
export type SchemaModelFormat = "delta_lake" | "hive" | "iceberg";
/**
 * Validate column name
 */
export type SchemaColumnName = string;
/**
 * Override the default partitioneds configuration for this model
 */
export type SchemaModelPartitions = SchemaColumnName[];
/**
 * Incremental Strategy
 */
export type ModelIncrementalStrategySchemaJson =
  | {
      type: "delete+insert";
      /**
       * Override the unique key(s) to use for merging
       */
      unique_key?: string | [string, ...string[]];
      [k: string]: unknown | undefined;
    }
  | {
      type: "merge";
      /**
       * The unique key(s) to use for merging
       */
      unique_key: string | [string, ...string[]];
      /**
       * The columns to exclude when merging
       */
      merge_exclude_columns?: string[];
      /**
       * The columns to update when merging
       */
      merge_update_columns?: string[];
      [k: string]: unknown | undefined;
    };
/**
 * Type of materialization
 */
export type SchemaModelMaterialized = "ephemeral" | "incremental";
/**
 * Override the default partitioned_by configuration for this model
 *
 * @minItems 1
 */
export type SchemaModelPartitionedBy = [SchemaColumnName, ...SchemaColumnName[]];
/**
 * Will prevent the automatic date filters from getting added
 */
export type SchemaModelExcludeDateFilter = boolean;
/**
 * Will prevent the automatic portal partition date columns from getting added
 */
export type SchemaModelExcludePortalPartitionColumns = boolean;
/**
 * Will prevent the automatic portal source count column from getting added
 */
export type SchemaModelExcludePortalSourceCount = boolean;
/**
 * Includes the full month when running any given event date
 */
export type ModelIncludeFullMonthSchemaJson = boolean;
/**
 * Use the events dates variable for the partition dates, skipping the dbt_source_dates table mapping
 */
export type ModelUseEventDatesForPartitionDatesSchemaJson = boolean;
/**
 * Validate selecting an existing named column
 */
export type SchemaModelSelectCol =
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      exclude_from_group_by?: SchemaColumnExcludeFromGroupBy;
      expr?: SchemaColumnExpr;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type?: "dim";
    }
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type: "fct";
    };
/**
 * Validate data_type scehma for columns
 */
export type SchemaColumnDataType =
  | "bigint"
  | "boolean"
  | "date"
  | "datetime"
  | "double"
  | "integer"
  | "number"
  | "row(date)"
  | "row(varchar)"
  | "string"
  | "timestamp"
  | "timestamp(0)"
  | "timestamp(3)"
  | "timestamp(6)"
  | "varchar";
/**
 * Description for the selected column
 */
export type SchemaColumnDescription = string;
/**
 * Exclude this dimension from group by when we are aggregating
 */
export type SchemaColumnExcludeFromGroupBy = boolean;
/**
 * SQL expression to be used when selecting the column (name will be the alias
 */
export type SchemaColumnExpr = string;
/**
 * Schema for lightdash AI hints
 */
export type SchemaLightdashAIHint = string | string[];
/**
 * Validate Lightdash metric name
 */
export type SchemaLightdashMetricName = string;
/**
 * Validate column data_tests
 */
export type SchemaColumnDataTests = (
  | ("not_null" | "unique")
  | {
      unique: {
        config: {
          where: SchemaColumnExpr;
        };
      };
    }
  | {
      accepted_values: {
        quote?: boolean;
        values: string[];
      };
    }
  | {
      relationships: {
        field: SchemaColumnName;
        to: string;
      };
    }
)[];
/**
 * Validate selecting a new column using an expression
 */
export type SchemaModelSelectExpr =
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      exclude_from_group_by?: SchemaColumnExcludeFromGroupBy;
      expr: SchemaColumnExpr;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type?: "dim";
    }
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      expr: SchemaColumnExpr;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type: "fct";
    };
/**
 * Validate model ids
 */
export type SchemaModelRef = string;
/**
 * Schema when selecting columns from a source
 */
export type SchemaModelSelectSource =
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      source: SchemaRefSourceId;
      data_tests?: SchemaColumnDataTests;
      type?: "dim" | "fct";
    }
  | {
      /**
       * @minItems 1
       */
      exclude?: [SchemaColumnName, ...SchemaColumnName[]];
      /**
       * @minItems 1
       */
      include?: [SchemaColumnName, ...SchemaColumnName[]];
      source: SchemaRefSourceId;
      type: "all_from_source";
    };
/**
 * Validate source ids
 */
export type SchemaRefSourceId = string;
/**
 * SQL WHERE
 */
export type SchemaModelWhere =
  | SchemaColumnExpr
  | {
      /**
       * Conditions to be combined by AND
       */
      and?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere;
      }[];
      /**
       * Conditions to be combined by OR
       */
      or?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere;
      }[];
    };
/**
 * Exclude Daily Filter
 */
export type ModelExcludeDailyFilterSchemaJson = boolean;
/**
 * Schema when selecting columns from another model
 */
export type SchemaModelSelectModel =
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      exclude_from_group_by?: boolean;
      lightdash?: SchemaColumnLightdash;
      model: SchemaModelRef;
      name: SchemaColumnName;
      override_prefix?: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type?: "dim";
    }
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      lightdash?: SchemaColumnLightdash;
      model: SchemaModelRef;
      name: SchemaColumnName;
      override_prefix?: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type: "fct";
    }
  | {
      type: "all_from_model" | "dims_from_model" | "fcts_from_model";
      /**
       * @minItems 1
       */
      exclude?: [SchemaColumnName, ...SchemaColumnName[]];
      /**
       * @minItems 1
       */
      include?: [SchemaColumnName, ...SchemaColumnName[]];
      model: SchemaModelRef;
      override_prefix?: SchemaColumnName;
    };
/**
 * Schema for lightdash required filters
 */
export type SchemaLightdashRequiredFilters = {
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: string;
}[];
/**
 * Validate model data_tests
 */
export type SchemaModelDataTests = {
  type: "unique";
  column_name: string;
}[];
/**
 * Validate model group by
 *
 * @minItems 1
 */
export type SchemaModelGroupBy = [
  (
    | string
    | {
        expr: string;
      }
    | {
        type: "dims";
      }
  ),
  ...(
    | string
    | {
        expr: string;
      }
    | {
        type: "dims";
      }
  )[]
];
/**
 * SQL HAVING
 */
export type SchemaModelHaving =
  | string
  | {
      /**
       * Conditions to be combined by AND
       */
      and?: {
        /**
         * SQL for the condition
         */
        expr?: string;
        group?: SchemaModelHaving;
      }[];
      /**
       * Conditions to be combined by OR
       */
      or?: {
        /**
         * SQL for the condition
         */
        expr?: string;
        group?: SchemaModelHaving;
      }[];
    };
/**
 * Validate model limit
 */
export type SchemaModelLimit = number;
/**
 * Validate model offset
 */
export type SchemaModelOffset = number;
/**
 * Validate model order by
 *
 * @minItems 1
 */
export type SchemaModelOrderBy = [
  (
    | SchemaColumnName
    | {
        name?: SchemaColumnName;
        type?: "asc" | "desc";
      }
  ),
  ...(
    | SchemaColumnName
    | {
        name?: SchemaColumnName;
        type?: "asc" | "desc";
      }
  )[]
];
/**
 * Validate selecting an existing named column and creating an agg
 */
export type SchemaModelSelectColWithAgg = {
  agg?: SchemaColumnAgg;
  aggs?: SchemaColumnAggs;
  data_type?: SchemaColumnDataType;
  description?: SchemaColumnDescription;
  lightdash?: SchemaColumnLightdash;
  name: SchemaColumnName;
  override_suffix_agg?: boolean;
  data_tests?: SchemaColumnDataTests;
  type: "fct";
};
/**
 * Automatically creates new aggregation columns, "hll" is HyperLogLog (used to approximate count distinct), and "tdigest" is T-Digest (used to approximate percentiles)
 */
export type SchemaColumnAgg = "count" | "hll" | "max" | "min" | "sum" | "tdigest";
/**
 * The aggregate functions to apply to the fact, this will generate a new column per agg specified, and automatically the agg type to the column name, e.g. column_count, column_sum. "hll" is HyperLogLog (used to approximate count distinct), and "tdigest" is T-Digest (used to approximate percentiles)
 *
 * @minItems 1
 */
export type SchemaColumnAggs = [SchemaColumnAgg, ...SchemaColumnAgg[]];
/**
 * Validate selecting a new column using an expression and creating an agg
 */
export type SchemaModelSelectExprWithAgg = {
  agg?: SchemaColumnAgg;
  aggs?: SchemaColumnAggs;
  data_type?: SchemaColumnDataType;
  description?: SchemaColumnDescription;
  expr: SchemaColumnExpr;
  lightdash?: SchemaColumnLightdash;
  name: SchemaColumnName;
  override_suffix_agg?: boolean;
  data_tests?: SchemaColumnDataTests;
  type: "fct";
};
/**
 * Schema when selecting columns from another model with an agg applied
 */
export type SchemaModelSelectModelWithAgg = {
  agg?: SchemaColumnAgg;
  aggs?: SchemaColumnAggs;
  data_type?: SchemaColumnDataType;
  description?: SchemaColumnDescription;
  lightdash?: SchemaColumnLightdash;
  model: SchemaModelRef;
  name: SchemaColumnName;
  override_prefix?: SchemaColumnName;
  override_suffix_agg?: boolean;
  data_tests?: SchemaColumnDataTests;
  type: "fct";
};
/**
 * Validates the join argument when joining multiple models
 *
 * @minItems 1
 */
export type SchemaModelFromJoinModels = [
  (
    | {
        model: SchemaModelRef;
        override_alias?: SchemaColumnName;
        type?: "cross";
      }
    | {
        model: SchemaModelRef;
        override_alias?: SchemaColumnName;
        type?: "full" | "inner" | "left" | "right";
        /**
         * SQL for the join condition
         */
        on: {
          /**
           * Conditions to be combined by AND
           */
          and?: (
            | SchemaColumnName
            | {
                /**
                 * SQL for the condition
                 */
                expr: string;
              }
          )[];
        };
      }
  ),
  ...(
    | {
        model: SchemaModelRef;
        override_alias?: SchemaColumnName;
        type?: "cross";
      }
    | {
        model: SchemaModelRef;
        override_alias?: SchemaColumnName;
        type?: "full" | "inner" | "left" | "right";
        /**
         * SQL for the join condition
         */
        on: {
          /**
           * Conditions to be combined by AND
           */
          and?: (
            | SchemaColumnName
            | {
                /**
                 * SQL for the condition
                 */
                expr: string;
              }
          )[];
        };
      }
  )[]
];

/**
 * Validates schema for staging models selecting from a source
 */
export interface SchemaModelTypeStgSelectSource {
  type: "stg_select_source";
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  tags?: SchemaModelTags;
  materialization?: SchemaModelMaterialization;
  materialized?: SchemaModelMaterialized;
  incremental_strategy?: ModelIncrementalStrategySchemaJson;
  sql_hooks?: ModelSqlHooksSchemaJson;
  partitioned_by?: SchemaModelPartitionedBy;
  exclude_date_filter?: SchemaModelExcludeDateFilter;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  include_full_month?: ModelIncludeFullMonthSchemaJson;
  use_event_dates_for_partition_dates?: ModelUseEventDatesForPartitionDatesSchemaJson;
  /**
   * @minItems 1
   */
  select: [
    (
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectExpr
      | SchemaModelSelectInterval
      | SchemaModelSelectSource
    ),
    ...(
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectExpr
      | SchemaModelSelectInterval
      | SchemaModelSelectSource
    )[]
  ];
  from: {
    source: SchemaRefSourceId;
  };
  where?: SchemaModelWhere;
}
/**
 * SQL statements to run before or after models
 */
export interface ModelSqlHooksSchemaJson {
  /**
   * Statement(s) to run after model
   */
  post?: string | [string, ...string[]];
  /**
   * Statement(s) to run before model
   */
  pre?: string | [string, ...string[]];
}
export interface SchemaColumnLightdash {
  dimension?: SchemaLightdashDimension;
  /**
   * @minItems 1
   */
  metrics?: [
    ("avg" | "count" | "distinctcount" | "max" | "min" | "p50" | "p90" | "p95" | "p98" | "sum") | SchemaLightdashMetric,
    ...(
      | ("avg" | "count" | "distinctcount" | "max" | "min" | "p50" | "p90" | "p95" | "p98" | "sum")
      | SchemaLightdashMetric
    )[]
  ];
  metrics_merge?: SchemaLightdashMetricMerge;
}
export interface SchemaLightdashDimension {
  ai_hint?: SchemaLightdashAIHint;
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  /**
   * The label that will be applied to the column in lightdash
   */
  label?: string;
  required_attributes?: SchemaLightdashRequiredAttributes;
  round?: number;
  format?: "eur" | "gbp" | "id" | "km" | "mi" | "percent" | "usd";
  /**
   * SQL statement to determine the dimension
   */
  sql?: string;
  /**
   * The time intervals for the lightdash dimension
   */
  time_intervals?:
    | "OFF"
    | (
        | "DAY"
        | "DAY_OF_WEEK_INDEX"
        | "DAY_OF_WEEK_NAME"
        | "DAY_OF_MONTH_NUM"
        | "DAY_OF_YEAR_NUM"
        | "HOUR"
        | "MONTH"
        | "MONTH_NAME"
        | "MONTH_NUM"
        | "QUARTER"
        | "QUARTER_NAME"
        | "QUARTER_NUM"
        | "RAW"
        | "WEEK"
        | "WEEK_NUM"
        | "YEAR"
        | "YEAR_NUM"
      )[];
  type?: "boolean" | "date" | "number" | "string" | "timestamp";
  /**
   * The URLs for the lightdash dimension
   */
  urls?: {
    /**
     * The label for the URL
     */
    label: string;
    /**
     * The URL to link to
     */
    url: string;
  }[];
}
/**
 * Schema for lightdash required attributes
 */
export interface SchemaLightdashRequiredAttributes {
  /**
   * This interface was referenced by `SchemaLightdashRequiredAttributes`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: string | string[];
}
export interface SchemaLightdashMetric {
  ai_hint?: SchemaLightdashAIHint;
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  /**
   * The compact status that will be applied to the column in lightdash
   */
  compact?: "thousands" | "millions" | "billions" | "trillions";
  /**
   * The description that will be applied to the column in lightdash
   */
  description?: string;
  /**
   * The label that will be applied to the column in lightdash
   */
  label?: string;
  name: SchemaLightdashMetricName;
  round?: number;
  format?: "eur" | "gbp" | "id" | "km" | "mi" | "percent" | "usd";
  /**
   * The custom sql expression to generate the metric
   */
  sql?: string;
  /**
   * The type of metric
   */
  type:
    | "average"
    | "boolean"
    | "count"
    | "count_distinct"
    | "date"
    | "max"
    | "median"
    | "min"
    | "number"
    | "percentile"
    | "string"
    | "sum";
}
/**
 * Values that can be merged in to override values on a metric
 */
export interface SchemaLightdashMetricMerge {
  /**
   * The compact status that will be applied to the column in lightdash
   */
  compact?: "thousands" | "millions" | "billions" | "trillions";
  format?: "eur" | "gbp" | "id" | "km" | "mi" | "percent" | "usd";
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  round?: number;
  /**
   * The custom sql expression to generate the metric
   */
  sql?: string;
}
export interface SchemaModelSelectInterval {
  description?: SchemaColumnDescription;
  interval: "day" | "hour" | "month" | "year";
  lightdash?: SchemaColumnLightdash;
  model?: SchemaModelRef;
  name: "datetime";
  data_tests?: SchemaColumnDataTests;
  type?: "dim";
}
/**
 * Validates schema for staging models selecting from a source
 */
export interface SchemaModelTypeStgSelectModel {
  type: "stg_select_model";
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  tags?: SchemaModelTags;
  materialization?: SchemaModelMaterialization;
  materialized?: SchemaModelMaterialized;
  incremental_strategy?: ModelIncrementalStrategySchemaJson;
  sql_hooks?: ModelSqlHooksSchemaJson;
  partitioned_by?: SchemaModelPartitionedBy;
  exclude_daily_filter?: ModelExcludeDailyFilterSchemaJson;
  exclude_date_filter?: SchemaModelExcludeDateFilter;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  where?: SchemaModelWhere;
  from: {
    model: SchemaModelRef;
  };
  /**
   * @minItems 1
   */
  select: [
    (
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectExpr
      | SchemaModelSelectInterval
      | SchemaModelSelectModel
    ),
    ...(
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectExpr
      | SchemaModelSelectInterval
      | SchemaModelSelectModel
    )[]
  ];
}
/**
 * Validates schema for staging models which union sources
 */
export interface SchemaModelTypeStgUnionSources {
  type: "stg_union_sources";
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  tags?: SchemaModelTags;
  materialization?: SchemaModelMaterialization;
  materialized?: SchemaModelMaterialized;
  incremental_strategy?: ModelIncrementalStrategySchemaJson;
  sql_hooks?: ModelSqlHooksSchemaJson;
  partitioned_by?: SchemaModelPartitionedBy;
  exclude_date_filter?: SchemaModelExcludeDateFilter;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  include_full_month?: ModelIncludeFullMonthSchemaJson;
  use_event_dates_for_partition_dates?: ModelUseEventDatesForPartitionDatesSchemaJson;
  /**
   * @minItems 1
   */
  select?: [
    (
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectExpr
      | SchemaModelSelectInterval
      | SchemaModelSelectSource
    ),
    ...(
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectExpr
      | SchemaModelSelectInterval
      | SchemaModelSelectSource
    )[]
  ];
  from: {
    source: SchemaRefSourceId;
    union: {
      type?: "all";
      sources: SchemaRefSourceId[];
    };
  };
  where?: SchemaModelWhere;
}
/**
 * Validates schema for int models selecting from a single model
 */
export interface SchemaModelTypeIntSelectModel {
  type: "int_select_model";
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  lightdash?: SchemaModelLightdash;
  tags?: SchemaModelTags;
  data_tests?: SchemaModelDataTests;
  materialization?: SchemaModelMaterialization;
  materialized?: SchemaModelMaterialized;
  incremental_strategy?: ModelIncrementalStrategySchemaJson;
  sql_hooks?: ModelSqlHooksSchemaJson;
  partitioned_by?: SchemaModelPartitionedBy;
  exclude_daily_filter?: ModelExcludeDailyFilterSchemaJson;
  exclude_date_filter?: SchemaModelExcludeDateFilter;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  group_by?: SchemaModelGroupBy;
  having?: SchemaModelHaving;
  limit?: SchemaModelLimit;
  offset?: SchemaModelOffset;
  order_by?: SchemaModelOrderBy;
  /**
   * @minItems 1
   */
  select: [
    (
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectColWithAgg
      | SchemaModelSelectExpr
      | SchemaModelSelectExprWithAgg
      | SchemaModelSelectInterval
      | SchemaModelSelectModel
      | SchemaModelSelectModelWithAgg
    ),
    ...(
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectColWithAgg
      | SchemaModelSelectExpr
      | SchemaModelSelectExprWithAgg
      | SchemaModelSelectInterval
      | SchemaModelSelectModel
      | SchemaModelSelectModelWithAgg
    )[]
  ];
  where?: SchemaModelWhere;
  from: {
    model: SchemaModelRef;
  };
}
/**
 * Validates schema for setting lightdash properties at the model level
 */
export interface SchemaModelLightdash {
  table?: SchemaLightdashTable;
  metrics?: SchemaLightdashMetric[];
  metrics_exclude?: SchemaLightdashMetricName[];
  metrics_include?: SchemaLightdashMetricName[];
}
export interface SchemaLightdashTable {
  ai_hint?: SchemaLightdashAIHint;
  group_details?: SchemaLightdashGroupDetails;
  group_label?: string;
  label?: string;
  required_attributes?: SchemaLightdashRequiredAttributes;
  required_filters?: SchemaLightdashRequiredFilters;
  sql_filter?: string;
  sql_where?: string;
}
/**
 * Schema for lightdash group details
 */
export interface SchemaLightdashGroupDetails {
  /**
   * This interface was referenced by `SchemaLightdashGroupDetails`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: {
    /**
     * The label of the group
     */
    label?: string;
    /**
     * The description of the group
     */
    description?: string;
  };
}
/**
 * Validates schema for int models which cross join on an unnested column
 */
export interface SchemaModelTypeIntJoinColumn {
  type: "int_join_column";
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  lightdash?: SchemaModelLightdash;
  tags?: SchemaModelTags;
  data_tests?: SchemaModelDataTests;
  materialization?: SchemaModelMaterialization;
  materialized?: SchemaModelMaterialized;
  incremental_strategy?: ModelIncrementalStrategySchemaJson;
  sql_hooks?: ModelSqlHooksSchemaJson;
  partitioned_by?: SchemaModelPartitionedBy;
  exclude_daily_filter?: ModelExcludeDailyFilterSchemaJson;
  exclude_date_filter?: SchemaModelExcludeDateFilter;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  group_by?: SchemaModelGroupBy;
  where?: SchemaModelWhere;
  /**
   * These columns will be selected in order from the unnested array column
   *
   * @minItems 1
   */
  select: [
    (
      | SchemaColumnName
      | {
          data_type?: SchemaColumnDataType;
          description?: SchemaColumnDescription;
          expr?: SchemaColumnExpr;
          lightdash?: SchemaColumnLightdash;
          name: SchemaColumnName;
          type?: "dim" | "fct";
        }
    ),
    ...(
      | SchemaColumnName
      | {
          data_type?: SchemaColumnDataType;
          description?: SchemaColumnDescription;
          expr?: SchemaColumnExpr;
          lightdash?: SchemaColumnLightdash;
          name: SchemaColumnName;
          type?: "dim" | "fct";
        }
    )[]
  ];
  from: {
    model: SchemaModelRef;
    join: SchemaModelFromJoinColumn;
  };
}
/**
 * Validates the join argument when joining to a column
 */
export interface SchemaModelFromJoinColumn {
  type?: "cross_join_unnest";
  column: SchemaColumnExpr;
  /**
   * @minItems 1
   */
  fields: [SchemaColumnExpr, ...SchemaColumnExpr[]];
}
/**
 * Validates schema for join models
 */
export interface SchemaModelTypeIntJoinModels {
  type: "int_join_models";
  group: SchemaModelGroup;
  topic?: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  lightdash?: SchemaModelLightdash;
  tags?: SchemaModelTags;
  data_tests?: SchemaModelDataTests;
  materialization?: SchemaModelMaterialization;
  materialized?: SchemaModelMaterialized;
  incremental_strategy?: ModelIncrementalStrategySchemaJson;
  sql_hooks?: ModelSqlHooksSchemaJson;
  partitioned_by?: SchemaModelPartitionedBy;
  exclude_daily_filter?: ModelExcludeDailyFilterSchemaJson;
  exclude_date_filter?: SchemaModelExcludeDateFilter;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  group_by?: SchemaModelGroupBy;
  having?: SchemaModelHaving;
  limit?: SchemaModelLimit;
  offset?: SchemaModelOffset;
  order_by?: SchemaModelOrderBy;
  where?: SchemaModelWhere;
  /**
   * @minItems 1
   */
  select: [
    SchemaModelSelectExpr | SchemaModelSelectInterval | SchemaModelSelectModel,
    ...(SchemaModelSelectExpr | SchemaModelSelectInterval | SchemaModelSelectModel)[]
  ];
  from: {
    join: SchemaModelFromJoinModels;
    model: SchemaModelRef;
  };
}
/**
 * Used for creating aggregated over a trailing time period
 */
export interface SchemaModelTypeIntLookbackModel {
  type: "int_lookback_model";
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  lightdash?: SchemaModelLightdash;
  tags?: SchemaModelTags;
  data_tests?: SchemaModelDataTests;
  materialization?: SchemaModelMaterialization;
  materialized?: SchemaModelMaterialized;
  incremental_strategy?: ModelIncrementalStrategySchemaJson;
  sql_hooks?: ModelSqlHooksSchemaJson;
  partitioned_by?: SchemaModelPartitionedBy;
  exclude_daily_filter?: ModelExcludeDailyFilterSchemaJson;
  exclude_date_filter?: SchemaModelExcludeDateFilter;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  /**
   * @minItems 1
   */
  select: [
    (
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectColWithAgg
      | SchemaModelSelectExpr
      | SchemaModelSelectExprWithAgg
      | SchemaModelSelectModel
      | SchemaModelSelectModelWithAgg
    ),
    ...(
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectColWithAgg
      | SchemaModelSelectExpr
      | SchemaModelSelectExprWithAgg
      | SchemaModelSelectModel
      | SchemaModelSelectModelWithAgg
    )[]
  ];
  from: {
    model: SchemaModelRef;
    lookback: {
      /**
       * The number of days to look back
       */
      days: number;
      /**
       * Exclude the event date from the lookback period (defaults to false)
       */
      exclude_event_date?: boolean;
    };
  };
  group_by?: SchemaModelGroupBy;
}
/**
 * Validates schema for rollup models
 */
export interface SchemaModelTypeIntRollupModel {
  type: "int_rollup_model";
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  lightdash?: SchemaModelLightdash;
  tags?: SchemaModelTags;
  data_tests?: SchemaModelDataTests;
  materialization?: SchemaModelMaterialization;
  materialized?: SchemaModelMaterialized;
  incremental_strategy?: ModelIncrementalStrategySchemaJson;
  sql_hooks?: ModelSqlHooksSchemaJson;
  partitioned_by?: SchemaModelPartitionedBy;
  exclude_daily_filter?: ModelExcludeDailyFilterSchemaJson;
  exclude_date_filter?: SchemaModelExcludeDateFilter;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  from: {
    model: SchemaModelRef;
    rollup: {
      datetime_expr?: string;
      /**
       * The interval for the rollup
       */
      interval: "day" | "hour" | "month" | "year";
    };
  };
}
/**
 * Validates schema for union models
 */
export interface SchemaModelTypeIntUnionModels {
  type: "int_union_models";
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  lightdash?: SchemaModelLightdash;
  tags?: SchemaModelTags;
  data_tests?: SchemaModelDataTests;
  materialization?: SchemaModelMaterialization;
  materialized?: SchemaModelMaterialized;
  incremental_strategy?: ModelIncrementalStrategySchemaJson;
  sql_hooks?: ModelSqlHooksSchemaJson;
  partitioned_by?: SchemaModelPartitionedBy;
  exclude_daily_filter?: ModelExcludeDailyFilterSchemaJson;
  exclude_date_filter?: SchemaModelExcludeDateFilter;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  /**
   * @minItems 1
   */
  select?: [SchemaModelSelectExpr | SchemaModelSelectModel, ...(SchemaModelSelectExpr | SchemaModelSelectModel)[]];
  from: {
    model: SchemaModelRef;
    union: {
      type?: "all";
      models: SchemaModelRef[];
    };
  };
  where?: SchemaModelWhere;
}
/**
 * Validates schema for models selecting from models
 */
export interface SchemaModelTypeMartSelectModel {
  type: "mart_select_model";
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  lightdash?: SchemaModelLightdash;
  tags?: SchemaModelTags;
  group_by?: SchemaModelGroupBy;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  /**
   * @minItems 1
   */
  select: [
    (
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectExpr
      | SchemaModelSelectInterval
      | SchemaModelSelectModel
    ),
    ...(
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectExpr
      | SchemaModelSelectInterval
      | SchemaModelSelectModel
    )[]
  ];
  from: {
    model: SchemaModelRef;
  };
}
/**
 * Validates schema for mart models which join multiple models
 */
export interface SchemaModelTypeMartJoinModels {
  type: "mart_join_models";
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  lightdash?: SchemaModelLightdash;
  tags?: SchemaModelTags;
  group_by?: SchemaModelGroupBy;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  /**
   * @minItems 1
   */
  select: [
    SchemaModelSelectExpr | SchemaModelSelectInterval | SchemaModelSelectModel,
    ...(SchemaModelSelectExpr | SchemaModelSelectInterval | SchemaModelSelectModel)[]
  ];
  where?: SchemaModelWhere;
  from: {
    join: SchemaModelFromJoinModels;
    model: SchemaModelRef;
  };
}
