/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Validate group reference
 */
export type SchemaModelGroup = string;
/**
 * Validate model topic
 */
export type SchemaModelTopic = string;
/**
 * Validate model name
 */
export type SchemaModelName = string;
/**
 * Description for the model that will appear as a hover tooltip in Lightdash
 */
export type SchemaModelDescription = string;
/**
 * Schema for lightdash AI hints
 */
export type SchemaLightdashAIHint = string | string[];
/**
 * Schema for lightdash required filters
 */
export type SchemaLightdashRequiredFilters = {
  /**
   * This interface was referenced by `undefined`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: string;
}[];
/**
 * Validate Lightdash metric name
 */
export type SchemaLightdashMetricName = string;
/**
 * Validate model tags
 */
export type SchemaModelTags = (
  | string
  | {
      tag: string;
      type?: "exclude" | "inherit" | "local";
    }
)[];
/**
 * Validate model group by
 *
 * @minItems 1
 */
export type SchemaModelGroupBy = [
  (
    | string
    | {
        expr: string;
      }
    | {
        type: "dims";
      }
  ),
  ...(
    | string
    | {
        expr: string;
      }
    | {
        type: "dims";
      }
  )[]
];
/**
 * Will prevent the automatic portal partition date columns from getting added
 */
export type SchemaModelExcludePortalPartitionColumns = boolean;
/**
 * Will prevent the automatic portal source count column from getting added
 */
export type SchemaModelExcludePortalSourceCount = boolean;
/**
 * Validate column name
 */
export type SchemaColumnName = string;
/**
 * Validate selecting an existing named column
 */
export type SchemaModelSelectCol =
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      exclude_from_group_by?: SchemaColumnExcludeFromGroupBy;
      expr?: SchemaColumnExpr;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type?: "dim";
    }
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type: "fct";
    };
/**
 * Validate data_type scehma for columns
 */
export type SchemaColumnDataType =
  | "bigint"
  | "boolean"
  | "date"
  | "datetime"
  | "double"
  | "integer"
  | "number"
  | "row(date)"
  | "row(varchar)"
  | "string"
  | "timestamp"
  | "timestamp(0)"
  | "timestamp(3)"
  | "timestamp(6)"
  | "varchar";
/**
 * Description for the selected column
 */
export type SchemaColumnDescription = string;
/**
 * Exclude this dimension from group by when we are aggregating
 */
export type SchemaColumnExcludeFromGroupBy = boolean;
/**
 * SQL expression to be used when selecting the column (name will be the alias
 */
export type SchemaColumnExpr = string;
/**
 * Validate column data_tests
 */
export type SchemaColumnDataTests = (
  | ("not_null" | "unique")
  | {
      unique: {
        config: {
          where: SchemaColumnExpr;
        };
      };
    }
  | {
      accepted_values: {
        quote?: boolean;
        values: string[];
      };
    }
  | {
      relationships: {
        field: SchemaColumnName;
        to: string;
      };
    }
)[];
/**
 * Validate selecting a new column using an expression
 */
export type SchemaModelSelectExpr =
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      exclude_from_group_by?: SchemaColumnExcludeFromGroupBy;
      expr: SchemaColumnExpr;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type?: "dim";
    }
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      expr: SchemaColumnExpr;
      lightdash?: SchemaColumnLightdash;
      name: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type: "fct";
    };
/**
 * Validate model ids
 */
export type SchemaModelRef = string;
/**
 * Schema when selecting columns from another model
 */
export type SchemaModelSelectModel =
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      exclude_from_group_by?: boolean;
      lightdash?: SchemaColumnLightdash;
      model: SchemaModelRef;
      name: SchemaColumnName;
      override_prefix?: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type?: "dim";
    }
  | {
      data_type?: SchemaColumnDataType;
      description?: SchemaColumnDescription;
      lightdash?: SchemaColumnLightdash;
      model: SchemaModelRef;
      name: SchemaColumnName;
      override_prefix?: SchemaColumnName;
      data_tests?: SchemaColumnDataTests;
      type: "fct";
    }
  | {
      type: "all_from_model" | "dims_from_model" | "fcts_from_model";
      /**
       * @minItems 1
       */
      exclude?: [SchemaColumnName, ...SchemaColumnName[]];
      /**
       * @minItems 1
       */
      include?: [SchemaColumnName, ...SchemaColumnName[]];
      model: SchemaModelRef;
      override_prefix?: SchemaColumnName;
    };

/**
 * Validates schema for models selecting from models
 */
export interface SchemaModelTypeMartSelectModel {
  type: "mart_select_model";
  group: SchemaModelGroup;
  topic: SchemaModelTopic;
  name: SchemaModelName;
  description?: SchemaModelDescription;
  lightdash?: SchemaModelLightdash;
  tags?: SchemaModelTags;
  group_by?: SchemaModelGroupBy;
  exclude_portal_partition_columns?: SchemaModelExcludePortalPartitionColumns;
  exclude_portal_source_count?: SchemaModelExcludePortalSourceCount;
  /**
   * @minItems 1
   */
  select: [
    (
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectExpr
      | SchemaModelSelectInterval
      | SchemaModelSelectModel
    ),
    ...(
      | SchemaColumnName
      | SchemaModelSelectCol
      | SchemaModelSelectExpr
      | SchemaModelSelectInterval
      | SchemaModelSelectModel
    )[]
  ];
  from: {
    model: SchemaModelRef;
  };
}
/**
 * Validates schema for setting lightdash properties at the model level
 */
export interface SchemaModelLightdash {
  table?: SchemaLightdashTable;
  metrics?: SchemaLightdashMetric[];
  metrics_exclude?: SchemaLightdashMetricName[];
  metrics_include?: SchemaLightdashMetricName[];
}
export interface SchemaLightdashTable {
  ai_hint?: SchemaLightdashAIHint;
  group_details?: SchemaLightdashGroupDetails;
  group_label?: string;
  label?: string;
  required_attributes?: SchemaLightdashRequiredAttributes;
  required_filters?: SchemaLightdashRequiredFilters;
  sql_filter?: string;
  sql_where?: string;
}
/**
 * Schema for lightdash group details
 */
export interface SchemaLightdashGroupDetails {
  /**
   * This interface was referenced by `SchemaLightdashGroupDetails`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: {
    /**
     * The label of the group
     */
    label?: string;
    /**
     * The description of the group
     */
    description?: string;
  };
}
/**
 * Schema for lightdash required attributes
 */
export interface SchemaLightdashRequiredAttributes {
  /**
   * This interface was referenced by `SchemaLightdashRequiredAttributes`'s JSON-Schema definition
   * via the `patternProperty` "^([A-z]|[0-9]|_|-)+$".
   */
  [k: string]: string | string[];
}
export interface SchemaLightdashMetric {
  ai_hint?: SchemaLightdashAIHint;
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  /**
   * The compact status that will be applied to the column in lightdash
   */
  compact?: "thousands" | "millions" | "billions" | "trillions";
  /**
   * The description that will be applied to the column in lightdash
   */
  description?: string;
  /**
   * The label that will be applied to the column in lightdash
   */
  label?: string;
  name: SchemaLightdashMetricName;
  round?: number;
  format?: "eur" | "gbp" | "id" | "km" | "mi" | "percent" | "usd";
  /**
   * The custom sql expression to generate the metric
   */
  sql?: string;
  /**
   * The type of metric
   */
  type:
    | "average"
    | "boolean"
    | "count"
    | "count_distinct"
    | "date"
    | "max"
    | "median"
    | "min"
    | "number"
    | "percentile"
    | "string"
    | "sum";
}
export interface SchemaColumnLightdash {
  dimension?: SchemaLightdashDimension;
  /**
   * @minItems 1
   */
  metrics?: [
    ("avg" | "count" | "distinctcount" | "max" | "min" | "p50" | "p90" | "p95" | "p98" | "sum") | SchemaLightdashMetric,
    ...(
      | ("avg" | "count" | "distinctcount" | "max" | "min" | "p50" | "p90" | "p95" | "p98" | "sum")
      | SchemaLightdashMetric
    )[]
  ];
  metrics_merge?: SchemaLightdashMetricMerge;
}
export interface SchemaLightdashDimension {
  ai_hint?: SchemaLightdashAIHint;
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  /**
   * The label that will be applied to the column in lightdash
   */
  label?: string;
  required_attributes?: SchemaLightdashRequiredAttributes;
  round?: number;
  format?: "eur" | "gbp" | "id" | "km" | "mi" | "percent" | "usd";
  /**
   * SQL statement to determine the dimension
   */
  sql?: string;
  /**
   * The time intervals for the lightdash dimension
   */
  time_intervals?:
    | "OFF"
    | (
        | "DAY"
        | "DAY_OF_WEEK_INDEX"
        | "DAY_OF_WEEK_NAME"
        | "DAY_OF_MONTH_NUM"
        | "DAY_OF_YEAR_NUM"
        | "HOUR"
        | "MONTH"
        | "MONTH_NAME"
        | "MONTH_NUM"
        | "QUARTER"
        | "QUARTER_NAME"
        | "QUARTER_NUM"
        | "RAW"
        | "WEEK"
        | "WEEK_NUM"
        | "YEAR"
        | "YEAR_NUM"
      )[];
  type?: "boolean" | "date" | "number" | "string" | "timestamp";
  /**
   * The URLs for the lightdash dimension
   */
  urls?: {
    /**
     * The label for the URL
     */
    label: string;
    /**
     * The URL to link to
     */
    url: string;
  }[];
}
/**
 * Values that can be merged in to override values on a metric
 */
export interface SchemaLightdashMetricMerge {
  /**
   * The compact status that will be applied to the column in lightdash
   */
  compact?: "thousands" | "millions" | "billions" | "trillions";
  format?: "eur" | "gbp" | "id" | "km" | "mi" | "percent" | "usd";
  /**
   * The group label that will be applied to the column in lightdash
   */
  group_label?: string;
  groups?: string[];
  /**
   * The hidden status that will be applied to the column in lightdash
   */
  hidden?: boolean;
  round?: number;
  /**
   * The custom sql expression to generate the metric
   */
  sql?: string;
}
export interface SchemaModelSelectInterval {
  description?: SchemaColumnDescription;
  interval: "day" | "hour" | "month" | "year";
  lightdash?: SchemaColumnLightdash;
  model?: SchemaModelRef;
  name: "datetime";
  data_tests?: SchemaColumnDataTests;
  type?: "dim";
}
