/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * SQL FROM with Model and Source Refs
 */
export type SchemaModelFrom =
  | {
      /**
       * The model reference
       */
      model: string;
      /**
       * Optional name for model to reference in joins
       */
      name?: string;
    }
  | SchemaModelFromTypeSource;

/**
 * Validate model from source and table
 */
export interface SchemaModelFromTypeSource {
  /**
   * The source reference
   */
  source: string;
  /**
   * The table reference
   */
  table: string;
}
