/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * SQL WHERE
 */
export type SchemaModelWhere =
  | SchemaColumnExpr
  | {
      /**
       * Conditions to be combined by AND
       */
      and?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere1;
      }[];
      /**
       * Conditions to be combined by OR
       */
      or?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere1;
      }[];
    };
/**
 * SQL expression to be used when selecting the column (name will be the alias
 */
export type SchemaColumnExpr = string;
/**
 * SQL WHERE
 */
export type SchemaModelWhere1 =
  | SchemaColumnExpr
  | {
      /**
       * Conditions to be combined by AND
       */
      and?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere1;
      }[];
      /**
       * Conditions to be combined by OR
       */
      or?: {
        expr?: SchemaColumnExpr;
        group?: SchemaModelWhere1;
      }[];
    };
