/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * SQL HAVING
 */
export type SchemaModelHaving =
  | string
  | {
      /**
       * Conditions to be combined by AND
       */
      and?: {
        /**
         * SQL for the condition
         */
        expr?: string;
        group?: SchemaModelHaving1;
      }[];
      /**
       * Conditions to be combined by OR
       */
      or?: {
        /**
         * SQL for the condition
         */
        expr?: string;
        group?: SchemaModelHaving1;
      }[];
    };
/**
 * SQL HAVING
 */
export type SchemaModelHaving1 =
  | string
  | {
      /**
       * Conditions to be combined by AND
       */
      and?: {
        /**
         * SQL for the condition
         */
        expr?: string;
        group?: SchemaModelHaving1;
      }[];
      /**
       * Conditions to be combined by OR
       */
      or?: {
        /**
         * SQL for the condition
         */
        expr?: string;
        group?: SchemaModelHaving1;
      }[];
    };
