/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Use the events dates variable for the partition dates, skipping the dbt_source_dates table mapping
 */
export type ModelUseEventDatesForPartitionDatesSchemaJson = boolean;
