/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The where clause expression
 */
export type SchemaColumnExpr = string;

/**
 * Applys a static "where" clause any time this source is queried
 */
export interface SchemaSourceWhere {
  expr: SchemaColumnExpr;
}
