/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Overrides any default settings for the portal_source_count column
 */
export interface SchemaSourcePortalSourceCount {
  /**
   * Explicitly exclude a portal_source_count column for this source
   */
  exclude?: boolean;
  /**
   * Custom label for the portal source count metric
   */
  metric_label?: string;
}
