/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Options when selecting columns from another source
 */
export type SchemaSourceSelect =
  | SchemaColumnName
  | {
      data_type?: string;
      expr?: string;
      name: SchemaColumnName;
    };
/**
 * Validate column name
 */
export type SchemaColumnName = string;
