export const SQL_COLORS: { [name: string]: string } = {
  bracket: '#da70d6',
  comment: '#6a9955',
  function: '#dcdcaa',
  keyword: '#569cd6',
  number: '#6a9955',
  string: '#ce9178',
  //   clear: '',
  //   identifier: '',
  //   special: '',
};

export const SQL_KEYWORDS = [
  'ADD',
  'ADD CONSTRAINT',
  'ALL',
  'ALTER',
  'ALTER COLUMN',
  'ALTER TABLE',
  'AND',
  'ANY',
  'AS',
  'ASC',
  'AUTO_INCREMENT',
  'BACKUP DATABASE',
  'BEGIN',
  'BETWEEN',
  'BINARY',
  'BLOB',
  'BY',
  'CASCADE',
  'CASE',
  'CHAR',
  'CHECK',
  'COLUMN',
  'COMMIT',
  'CONSTRAINT',
  'CREATE',
  'CREATE DATABASE',
  'CREATE INDEX',
  'CREATE OR REPLACE VIEW',
  'CREATE PROCEDURE',
  'CREATE TABLE',
  'CREATE UNIQUE INDEX',
  'CREATE VIEW',
  'CURRENT_DATE',
  'CURRENT_TIME',
  'DATABASE',
  // 'DATETIME',
  'DECIMAL',
  'DEFAULT',
  'DELETE',
  'DESC',
  'DISTINCT',
  'DROP',
  'DROP COLUMN',
  'DROP CONSTRAINT',
  'DROP DATABASE',
  'DROP DEFAULT',
  'DROP INDEX',
  'DROP TABLE',
  'DROP VIEW',
  'EACH',
  'ELSE',
  'ELSEIF',
  'END',
  'ENGINE',
  'EXEC',
  'EXISTS',
  'FALSE',
  'FOR',
  'FOREIGN KEY',
  'FROM',
  'FULL OUTER JOIN',
  'GROUP',
  'GROUP BY',
  'HAVING',
  'IF',
  'IFNULL',
  'ILIKE',
  'IN',
  'INDEX',
  'INDEX_LIST',
  'INNER JOIN',
  'INSERT',
  'INSERT INTO',
  'INSERT INTO SELECT',
  'INTEGER',
  'INTERVAL',
  'INTO',
  'IS',
  'IS NOT NULL',
  'IS NULL',
  'JOIN',
  'KEY',
  'KEYS',
  'LEADING',
  'LEFT',
  'LEFT JOIN',
  'LIKE',
  'LIMIT',
  'LONGTEXT',
  'MATCH',
  'NOT',
  'NOT NULL',
  'NULL',
  'ON',
  'OPTION',
  'OR',
  'ORDER',
  'ORDER BY',
  'OUT',
  'OUTER',
  'OUTER JOIN',
  'OVERLAPS',
  'PRAGMA',
  'PRIMARY',
  'PRIMARY KEY',
  'PRINT',
  'PROCEDURE',
  'REFERENCES',
  'REPLACE',
  'RETURNING',
  'RIGHT',
  'RIGHT JOIN',
  'ROWNUM',
  'SELECT',
  'SELECT DISTINCT',
  'SELECT INTO',
  'SELECT TOP',
  'SET',
  'SHOW',
  'TABLE',
  // 'TIMESTAMP',
  'TEXT',
  'THEN',
  'TINYBLOB',
  'TINYINT',
  'TINYTEXT',
  'TO',
  'TOP',
  'TRAILING',
  'TRUE',
  'TRUNCATE TABLE',
  'UNION',
  'UNION ALL',
  'UNIQUE',
  'UNSIGNED',
  'UPDATE',
  'VALUE',
  'VALUES',
  'VARBINARY',
  'VARCHAR',
  'VIEW',
  'WHEN',
  'WHERE',
  'WITH',
];

export const SQL_HIGHLIGHTERS = [
  /(?<number>[+-]?(?:\d+\.\d+|\d+|\.\d+)(?:E[+-]?\d+)?)/,

  // Note: Repeating string escapes like 'sql''server' will also work as they are just repeating strings
  /(?<string>'(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")/,

  /(?<comment>--[^\n\r]*|#[^\n\r]*|\/\*(?:[^*]|\*(?!\/))*\*\/)/,

  // Future improvement: Comments should be allowed between the function name and the opening parenthesis
  /\b(?<function>\w+)(?=\s*\()/,

  /(?<bracket>[()])/,

  /(?<identifier>\b\w+\b|`(?:[^`\\]|\\.)*`)/,

  /(?<whitespace>\s+)/,

  // Multi-character arithmetic, bitwise, comparison, and compound operators as listed in
  // https://www.w3schools.com/sql/sql_operators.asp, https://www.tutorialspoint.com/sql/sql-operators.htm,
  // https://data-flair.training/blogs/sql-operators/, plus any single character (in particular ,:;.) not matched by
  // the above regexps.
  /(?<special>\^-=|\|\*=|\+=|-=|\*=|\/=|%=|&=|>=|<=|<>|!=|!<|!>|>>|<<|.)/,
];
